#!/bin/sh
# Directives
#PBS -N binoy_job1
#PBS -W group_list=yeticheme
#PBS -l walltime=12:00:00
#PBS -m n
#PBS -V

# Set output and error directories
#PBS -o localhost:/vega/cheme/users/st2663/outputs/binoy/records
#PBS -e localhost:/vega/cheme/users/st2663/outputs/binoy/records

# detached ring simulation
# change from original: use ActoMyosin_v1.1.tcl
# change from v1: isotropic Myp2p, use matlab_to_gro_fin3_march.m
# change from v2: use ActoMyosin_v1.2.tcl

# looping through all files with format .mat in current directory
for file in *.mat
do

#variable for file name
FNAME="$file" 
FNAME=${FNAME/.mat/}

#variable to substitute the correct time for each image
#on line 26 change 'min' to 'us' for depending on file format for run
FTIME=${FNAME:8}
FTIME=${FTIME/min/}
TEN=10

#comment out the following line if 'us' is in file format
#FTIME=$((FTIME - TEN))

#variable for run time for file in seconds, comment out if time in 'min'
#FTIME=$((FTIME/1000))  

# sathish change
FTIME=0

#opening matlab to run scripts
module load matlab/2015a
matlab -nosplash -nodisplay -nodesktop -r "matlab_to_gro_fin5('$FNAME.mat');quit"

#substituting values for each filename in the tcl file using the sed command
sed s/test/$FNAME/ < ActoMyosin_v1.2.side.tcl > ActoMyosinRun.tcl

#change min to s for seconds file format
sed -i s/time/"$FTIME min"/  ActoMyosinRun.tcl
/vega/cheme/users/st2663/vmd/bin/vmd -dispdev text -e ActoMyosinRun.tcl

#changing the tga image file generated by vmd to a higher resolution .png file
#convert ${FNAME}_top.tga ${FNAME}_top.png

#the following line can be commented out and the above can be commented in 
#(with corresponding procedure in ActoMyosin.tcl) to generate side view
convert ${FNAME}_side.tga ${FNAME}_side.png
done

# running movie making script to stitch all images together to make a .avi video file
# matlab -nosplash -nodisplay -nodesktop -r "make_movie1(1);quit"
# End of script
