#!/bin/sh
#opening matlab to run scripts
module load matlab
matlab -nosplash -nodisplay -nodesktop -r "matlab_to_gro_fin5('$1.mat');quit"

#substituting values for each filename in the tcl file using the sed command
sed s/test/$1/ < ActoMyosin_v1.2.tcl > tcl/ActoMyosinRun${1}.tcl

#change min to s for seconds file format
C=`echo ${1}.mat | awk -F'_' '{print $3}' | awk -F'min' '{print $1}' | sed 's/p1/.25/g' | sed 's/p2/.5/g' | sed 's/p3/.75/g'`
D=`echo $C - 11 | bc`
B=`printf "%.2f" "$D"`
sed -i s/time/"$B min"/  tcl/ActoMyosinRun${1}.tcl

# check if an off file that corresponds to this particular
# ring is present, then use that file to generate a tcl file
# and use that to make the septum
# instead of the generic septum.tcl

FILE=$1_septum.off
if [ -f "$FILE" ]; then
	matlab -nosplash -nodisplay -nodesktop -r "off_to_tcl('$1_septum.off');quit"
	sed -i s/septum\.tcl/$1_septum\.tcl/  tcl/ActoMyosinRun${1}.tcl
fi

/rigel/cheme/users/st2663/vmd/bin/vmd -dispdev text -eofexit < tcl/ActoMyosinRun${1}.tcl > log/output${1}.log

#changing the tga image file generated by vmd to a higher resolution .png file
convert ${1}_top.tga png/${1}_top.png
rm ${1}_top.tga
